name: ftpconnect
description: Simple and robust dart FTP Connect Library to interact with FTP Servers.
version: 2.3.0
#author: Salim Lachdhaf
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/dartFTP
repository: https://github.com/salim-lachdhaf/dartFTP

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.1
  intl: ^0.20.3
  dartssh2: ^3.3.1

dev_dependencies:
  test: ^1.31.2
  coverage: ^1.15.1
  pana: ^0.23.18
  lints: ^6.1.0

topics:
  - sftp
  - ftp
  - ftpes
  - ftps
  - ftp-client